### ISSUE TITLE
making a binder image

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-community-tutorials#7]
@aasfaw if you want to make a binder image from this you will need a file apt.txt with the following. I am not suggesting that you do it but this is how we made the binder image on the old tutorials and if you want to repeat it here this is the file you need. 

texlive-latex-base
texlive-latex-recommended
texlive-science
texlive-latex-extra
texlive-fonts-recommended
dvipng
ghostscript
poppler-utils

**Comment by aasfaw** [comment]
Got it @jaygambetta

**Comment by JanLahmann** [comment]
Any estimate when this patch (Adding binder #34) will be merged to make binder work again for the community tutorials?

**Comment by omarcostahamido** [comment]
Thank you @JanLahmann for the reference to my pull request. It was merged just now ;)
